package katas

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

object EvenFibonacci {
  def apply() = {
    lazy val fibs: Stream[Int] = 0 #:: fibs.scanLeft(1)(_ + _)
    fibs.filter({
      n => n % 2 == 0
    }).takeWhile(_ < 4000000).toList.sum
  }
}
